// Code generated by protoc-gen-go. DO NOT EDIT.
// source: micro.proto

/*
Package microproto is a generated protocol buffer package.

It is generated from these files:
	micro.proto

It has these top-level messages:
	Request
	Response
*/
package microproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Method string `protobuf:"bytes,1,opt,name=method" json:"method,omitempty"`
	Id     uint64 `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Params []byte `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	Ext    []byte `protobuf:"bytes,4,opt,name=ext,proto3" json:"ext,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Request) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Request) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Request) GetParams() []byte {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *Request) GetExt() []byte {
	if m != nil {
		return m.Ext
	}
	return nil
}

type Response struct {
	Id     uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Code   int32  `protobuf:"varint,2,opt,name=code" json:"code,omitempty"`
	Result []byte `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Ext    []byte `protobuf:"bytes,4,opt,name=ext,proto3" json:"ext,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Response) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *Response) GetExt() []byte {
	if m != nil {
		return m.Ext
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "micromicroproto.Request")
	proto.RegisterType((*Response)(nil), "microproto.Response")
}

func init() { proto.RegisterFile("micro.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 164 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0xce, 0xb1, 0x0a, 0xc2, 0x30,
	0x10, 0xc6, 0x71, 0xd2, 0xd6, 0xaa, 0xa7, 0x88, 0x64, 0x90, 0x8c, 0xa5, 0x53, 0x27, 0x17, 0xdf,
	0xe4, 0x26, 0xc1, 0xa9, 0x36, 0x07, 0x16, 0xac, 0x17, 0x93, 0x14, 0x7c, 0x7c, 0xc9, 0x19, 0x5d,
	0xdc, 0xbe, 0x7f, 0x08, 0x3f, 0x0e, 0x36, 0xd3, 0x38, 0x78, 0x3e, 0x3a, 0xcf, 0x91, 0x35, 0x48,
	0xc8, 0x6e, 0x2f, 0xb0, 0x44, 0x7a, 0xce, 0x14, 0xa2, 0x3e, 0x40, 0x3d, 0x51, 0xbc, 0xb1, 0x35,
	0xaa, 0x51, 0xdd, 0x1a, 0x73, 0xe9, 0x1d, 0x14, 0xa3, 0x35, 0x45, 0xa3, 0xba, 0x0a, 0x8b, 0xd1,
	0xa6, 0x7f, 0xae, 0xf7, 0xfd, 0x14, 0x4c, 0xd9, 0xa8, 0x6e, 0x8b, 0xb9, 0xf4, 0x1e, 0x4a, 0x7a,
	0x45, 0x53, 0xc9, 0x63, 0x9a, 0xed, 0x19, 0x56, 0x48, 0xc1, 0xf1, 0x23, 0x50, 0x56, 0xd4, 0x4f,
	0xd1, 0x50, 0x0d, 0x6c, 0x49, 0xdc, 0x05, 0xca, 0x4e, 0xb2, 0xa7, 0x30, 0xdf, 0xe3, 0x57, 0xfe,
	0xd4, 0xbf, 0x7c, 0xad, 0xe5, 0xfa, 0xd3, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x35, 0x97, 0xb7, 0x81,
	0xd8, 0x00, 0x00, 0x00,
}
